[package]
name = "registry_test_helper"
version = "0.1.1"
edition = "2021"

[net]
git-fetch-with-cli = true

[dependencies]
sbor = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.1.1" }
scrypto = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.1.1" }
transaction = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.1.1" }
radix-engine = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.1.1" }
scrypto-unit = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.1.1" }
radix-engine-stores = { git = "https://github.com/radixdlt/radixdlt-scrypto", tag = "v1.1.1" }
scrypto_testenv = { git = "https://github.com/ociswap/scrypto-testenv", tag = "v0.7.0-alpha.5" }
# common = { git = "https://github.com/ociswap/pools-common" }
common = { git = "ssh://git@github.com/ociswap/pools-common.git" }
pretty_assertions = "1.3.0"
lazy_static = "1.4.0"

[features]
default = []
test = []

[lib]
crate-type = ["cdylib", "lib"]
