[package]
name = "registry_test_helper"
version = "0.1.1"
edition = "2021"

[dependencies]
sbor = "1.3.0"
scrypto = "1.3.0"
radix-engine = "1.3.0"
scrypto_testenv = { git = "https://github.com/ociswap/scrypto-testenv", tag = "v0.8.0" }
pretty_assertions = "1.3.0"
lazy_static = "1.4.0"
